Revert of tcmalloc: Use C++11 atomics where appropriate. (patchset #9 id:160001 of https://codereview.chromium.org/1549913002/ )
Reason for revert:
Doesn't build on 32-bit: https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.linux%2FLinux_Builder__dbg__32_%2F66018%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

../../build/linux/debian_jessie_i386-sysroot/usr/lib/gcc/i586-linux-gnu/4.8/../../../../include/c++/4.8/bits/atomic_base.h:506: error: undefined reference to '__atomic_load_8'
../../build/linux/debian_jessie_i386-sysroot/usr/lib/gcc/i586-linux-gnu/4.8/../../../../include/c++/4.8/bits/atomic_base.h:486: error: undefined reference to '__atomic_store_8'

Original issue's description:
> tcmalloc: Use C++11 atomics where appropriate.
>
> Reland now that we have a newer sysroot.
>
> Ports these CLs to tcmalloc:
> https://codereview.chromium.org/636783002/
> https://codereview.chromium.org/1466833002/ (except mac)
>
> No intended behavior change, but it should remove
> the static initializer in atomicops_internals_x86_gcc.h
> on Linux.  It's also less code.
>
> BUG=94925,559247,572525
>
> Committed: https://crrev.com/08792198b88ccc8c79aace5977c21af3079f435e
> Cr-Original-Commit-Position: refs/heads/master@{#366904}
> Review-Url: https://codereview.chromium.org/1549913002
> Cr-Commit-Position: refs/heads/master@{#464440}
> Committed: https://chromium.googlesource.com/chromium/src/+/239404f3f36d75b0203f0d3b8fb3731c2d08dca4

TBR=jfb@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=94925,559247,572525

Review-Url: https://codereview.chromium.org/2818713003
Cr-Commit-Position: refs/heads/master@{#464445}