GCC: fix build error because of assuming ByteSwapUintPtrT is constexpr
The usage of ByteSwapUintPtrT in constexpr functions fails because it
is not declared as constexpr. To fix that problem, it is enough to
declare it and the function it calls as constexpr.

Fixes this GCC build bug:
    ../../base/allocator/partition_allocator/partition_freelist_entry.h: In static member function ‘static constexpr uintptr_t base::internal::EncodedPartitionFreelistEntryPtr::Transform(uintptr_t)’:
    ../../base/allocator/partition_allocator/partition_freelist_entry.h:74:45: error: call to non-‘constexpr’ function ‘uintptr_t base::ByteSwapUintPtrT(uintptr_t)’

Bug: 819294
Change-Id: I3606bd3469dbba36ee35015e1b7960e49363e3cb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3436948
Reviewed-by: Francois Pierre Doray <fdoray@chromium.org>
Commit-Queue: Francois Pierre Doray <fdoray@chromium.org>
Cr-Commit-Position: refs/heads/main@{#967255}