Revert "base/android: Remove linker tests support."
This reverts commit a22270236797ce3ee799adeff4350afff94a2adc.

Reason for revert: Suspect for compile failure https://ci.chromium.org/p/chromium/builders/ci/android-archive-rel/9949?

../../content/shell/android/linker_test_apk/src/org/chromium/chromium_linker_test_apk/LinkerTests.java:16: error: cannot find symbol
public class LinkerTests implements Linker.TestRunner {
                                          ^
  symbol:   class TestRunner
  location: class Linker

Original change's description:
> base/android: Remove linker tests support.
> 
> The linker tests don't run on bots (and likely not locally either) and
> do not support the latest library loading patterns. This is the first
> step to remove them, as they add non-trivial complexity in the codebase.
> 
> Bug: 1059707
> Change-Id: Ia14693419792f57dc4f65b2fc7f999e833aec42e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2095059
> Reviewed-by: Yaron Friedman <yfriedman@chromium.org>
> Reviewed-by: Egor Pasko <pasko@chromium.org>
> Commit-Queue: Benoit L <lizeb@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#748365}

TBR=pasko@chromium.org,yfriedman@chromium.org,lizeb@chromium.org

Change-Id: Ib45bd99a42903407e92dfb4a386b31ec0e7f7ee1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1059707
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2095777
Reviewed-by: Kevin McNee <mcnee@chromium.org>
Commit-Queue: Kevin McNee <mcnee@chromium.org>
Cr-Commit-Position: refs/heads/master@{#748390}