Revert of base: Remove operator& from ScopedAuthorizationRef. (patchset #1 id:1 of https://codereview.chromium.org/986563003/)
Reason for revert:
Breaks the official Mac bot:

../../remoting/host/installer/mac/uninstaller/remoting_uninstaller.mm:155:21:error: no matching function for call to 'AuthorizationCreate'
  OSStatus status = AuthorizationCreate(nullptr, kAuthorizationEmptyEnvironment,
                    ^~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/Security.framework/Headers/Authorization.h:253:10: note: candidate function not viable: no known conversion from 'base::mac::ScopedAuthorizationRef *' to 'AuthorizationRef *' (aka 'const AuthorizationOpaqueRef **') for 4th argument
OSStatus AuthorizationCreate(const AuthorizationRights *rights,

Original issue's description:
> base: Remove operator& from ScopedAuthorizationRef.
>
> The operator& is dangerous and makes it unclear what you are doing.
> Replace it with a get_pointer() method.
>
> R=Nico
> BUG=464816
>
> Committed: https://crrev.com/e40ab093c9a2680ed453d63c1841a93a18914556
> Cr-Commit-Position: refs/heads/master@{#319565}

TBR=thakis@chromium.org,danakj@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=464816

Review URL: https://codereview.chromium.org/988113002

Cr-Commit-Position: refs/heads/master@{#319570}