Revert "Remove/replace unnecessary includes of logging.h (base/)"
This reverts commit 64225a4087bb0c931ad36bea71887d5678b97629.

Reason for revert: this broke the win-chrome and win64-chrome
continuous builders. For the win-chrome build this CL was one of two
on the blamelist, for win64-chrome it was the only one.

Failure is:

FAILED: obj/chrome/browser/browser/widevine_hardware_caps_win.obj
c:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
../../chrome/browser/media/widevine_hardware_caps_win.cc(13,3): error: use of undeclared identifier 'NOTIMPLEMENTED'
NOTIMPLEMENTED();
^
1 error generated.

Original change's description:
> Remove/replace unnecessary includes of logging.h (base/)
>
> If the file just needs the CHECK/CHECK_OP/NOTREACHED
> macros, use the appropriate header for that instead.
> Or if logging.h is not needed at all, remove it.
>
> This is both a nice cleanup (logging.h is a big header,
> and including it unnecessarily has compile-time costs),
> and part of the final step towards making logging.h no
> longer include check.h and the others.
>
> TBR=thakis
>
> Bug: 1031540
> Change-Id: Ib87efde411a3617fcebad6dae08313c20d63d0bd
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2254284
> Commit-Queue: Hans Wennborg <hans@chromium.org>
> Reviewed-by: Nico Weber <thakis@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#780580}

TBR=thakis@chromium.org,hans@chromium.org

Change-Id: Iea5fb95ca6e84da2668dbfa139f1dc866311d7de
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1031540
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2256151
Commit-Queue: Bruce Dawson <brucedawson@chromium.org>
Reviewed-by: Bruce Dawson <brucedawson@chromium.org>
Cr-Commit-Position: refs/heads/master@{#780587}