Revert of Default components to static libraries in GN build (patchset #15 id:280001 of https://codereview.chromium.org/2043873004/ )
Reason for revert:
This CL causes Win x64 Builder (Perf) compilation error:

FAILED: obj/third_party/WebKit/Source/modules/blink_modules.lib
C:/b/depot_tools/python276_bin/python.exe gyp-win-tool link-wrapper environment.x64 False lib.exe /nologo /ignore:4221 /LTCG /LTCG /LTCG /LTCG /OUT:obj/third_party/WebKit/Source/modules/blink_modules.lib @obj/third_party/WebKit/Source/modules/blink_modules.lib.rsp
obj/third_party/WebKit/Source/modules/blink_modules.lib : fatal error LNK1248: image size (10061341C) exceeds maximum allowable size (FFFFFFFF)

[791/850] LINK(DLL) mus_library.dll mus_library.dll.lib
[792/850] LINK cc_perftests.exe
ninja: build stopped: subcommand failed.

Also see http://crbug.com/619606.

Original issue's description:
> Default components to static libraries in GN build
>
> Previously components would be source sets in non-component mode. Some test targets link large components in chrome but use almost none of them, and including all object files makes these links very slow.
>
> BUG=617837
> CQ_INCLUDE_TRYBOTS=tryserver.chromium.linux:linux_optional_gpu_tests_rel;tryserver.chromium.mac:mac_optional_gpu_tests_rel;tryserver.chromium.win:win_optional_gpu_tests_rel
>
> Committed: https://crrev.com/64ea1986c2f1a9aeec9e12240fd993d726509da8
> Cr-Commit-Position: refs/heads/master@{#399406}

TBR=jam@chromium.org,brucedawson@chromium.org,brettw@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=617837

Review-Url: https://codereview.chromium.org/2065633002
Cr-Commit-Position: refs/heads/master@{#399471}