Revert "Use the Windows MDM API to check if the machine is being managed."
This reverts commit 811e5a4f0df8b655215b063dbb9f8cb8fdd1434e.

Commit causes failures on Google Chrome ChromeOS and
Google Chrome Win:

../../components/update_client/utils.cc:171:39: error: 'IsEnterpriseManaged' is a private member of 'update_client::UpdaterState'
      if (attr.first != UpdaterState::IsEnterpriseManaged) {

BUG=690163
TBR=rogerta@chromium.org,sky@chromium.org,asvitkine@chromium.org,grt@chromium.org,avi@chromium.org,waffles@chromium.org,georgesak@chromium.org,pastarmovj@chromium.org

Review-Url: https://codereview.chromium.org/2710713004
Cr-Commit-Position: refs/heads/master@{#452068}