Revert of Enable the ninja parsing code all the time. (https://codereview.chromium.org/270333002/)
Reason for revert:
Speculative revert. Maybe the cause of various bot failures involving "A .isolate file is required"

Logs:
http://build.chromium.org/p/chromium.linux/builders/Linux%20Tests/builds/10820
http://build.chromium.org/p/chromium.win/builders/Vista%20Tests%20%283%29/builds/39788

Snippet from Linux Tests log:
/usr/bin/python
/mnt/data/b/build/slave/Linux_Tests/build/src/tools/swarming_client/isolate.py
run --isolated
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/interactive_ui_tests.isolated
-v -- --no-cr --test-launcher-bot-mode
--gtest_output=xml:/mnt/data/b/build/slave/Linux_Tests/build/gtest-results/interactive_ui_tests/interactive_ui_tests.xml
--test-launcher-summary-output=/tmp/tmpldQYtj
[------ Swarming Error ------]
A .isolate file is required.
Traceback (most recent call last):
  File
"/mnt/data/b/build/slave/Linux_Tests/build/src/tools/swarming_client/isolate.py",
line 1516, in main
    return dispatcher.execute(OptionParserIsolate(version=__version__), argv)
  File
"/mnt/data/b/build/slave/Linux_Tests/build/src/tools/swarming_client/third_party/depot_tools/subcommand.py",
line 242, in execute
    return command(parser, args[1:])
  File
"/mnt/data/b/build/slave/Linux_Tests/build/src/tools/swarming_client/isolate.py",
line 1251, in CMDrun
    options, os.getcwd(), None, options.skip_refresh)
  File
"/mnt/data/b/build/slave/Linux_Tests/build/src/tools/swarming_client/isolate.py",
line 863, in load_complete_state
    raise ExecutionError('A .isolate file is required.')
ExecutionError: A .isolate file is required.

Original issue's description:
> isolate_driver: Enable ninja parsing code all the time.
> 
> Split the ninja parsing code in its own file so that isolate_driver is focused
> on .isolate management.
> 
> - This removes the need to specify the majority of binary runtime dependencies.
>   Sadly, this means a few unrelated binaries are now pulled in, for example d8,
>   libvpx_obj_int_extract and tls_edit. That's a maintenance/performance trade
>   off.
> - Removed some dependencies for unit_tests.isolate to ensure this works.
> 
> R=vadimsh@chromium.org
> BUG=368543
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=269140

TBR=vadimsh@chromium.org,maruel@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=368543

Review URL: https://codereview.chromium.org/272113002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@269163 0039d316-1c4b-4281-b951-d872f2087c98