Revert of Remove base/move.h (patchset #4 id:60001 of https://codereview.chromium.org/2038273002/ )
Reason for revert:
This breaks the Windows build on the waterfall.
The error log is:
https://build.chromium.org/p/tryserver.chromium.win/builders/win_chromium_compile_dbg_ng/builds/202064/steps/compile%20%28with%20patch%29/logs/stdio

FAILED: obj/ash/mus/lib/shelf_layout_impl.obj
ninja -t msvc -e environment.x86 -- E:\b\build\slave\cache\cipd\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/ash/mus/lib/shelf_layout_impl.obj.rsp /c ../../ash/mus/shelf_layout_impl.cc /Foobj/ash/mus/lib/shelf_layout_impl.obj /Fd"obj/ash/mus/lib_cc.pdb"
e:\b\build\slave\win\build\src\base\template_util.h(65): error C2718: 'ui::LatencyInfo': actual parameter with requested alignment of 8 won't be aligned
e:\b\build\slave\win\build\src\base\template_util.h(86): note: see reference to class template instantiation 'base::internal::IsAssignableImpl<Lvalue,Rvalue,false>' being compiled
        with
        [
            Lvalue=ui::LatencyInfo &,
            Rvalue=ui::LatencyInfo &&
        ]
e:\b\build\slave\win\build\src\base\template_util.h(103): note: see reference to class template instantiation 'base::is_assignable<ui::LatencyInfo &,ui::LatencyInfo &&>' being compiled
e:\b\build\slave\win\build\src\mojo\public\cpp\bindings\lib\template_util.h(58): note: see reference to class template instantiation 'base::is_move_assignable<T>' being compiled
        with
        [
            T=ui::LatencyInfo
        ]
e:\b\build\slave\win\build\src\mojo\public\cpp\bindings\array.h(34): note: see reference to class template instantiation 'mojo::internal::IsMoveOnlyType<MojomType>' being compiled
        with
        [
            MojomType=ui::LatencyInfo
        ]
e:\b\build\slave\win\build\src\out\debug\gen\cc\ipc\compositor_frame_metadata.mojom.h(121): note: see reference to class template instantiation 'mojo::Array<ui::LatencyInfo>' being compiled

Original issue's description:
> Remove base/move.h
>
> It's the same thing as DISALLOW_COPY_AND_ASSIGN now anyway.
>
> BUG=566182
>
> Committed: https://crrev.com/1dd0aede0301fe7c977dd4b09918da7a1e31c4c5
> Cr-Commit-Position: refs/heads/master@{#398237}

TBR=thakis@chromium.org,yzshen@chromium.org,jam@chromium.org,dcheng@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=566182

Review-Url: https://codereview.chromium.org/2047633002
Cr-Commit-Position: refs/heads/master@{#398239}