Revert "Use assumevalues instead of assumenosideffects for proguard."
This reverts commit ca0470b1aa77c6871e3f9b1586b3a4e21320f7cd.

Reason for revert: Broke https://ci.chromium.org/p/chrome/builders/ci/android_arm64-builder-perf

util.build_utils.CalledProcessError: Command failed: ( cd /b/s/w/ir/cache/builder/src/out/Release; java -jar ../../third_party/r8/lib/r8.jar --no-desugaring --no-data-resources [...] lib.java/clank/third_party/compressed_resources/LemonStandaloneRuntime.jar lib.java/clank/java/build_hooks_android_impl_java.jar )
In ../../base/android/proguard/chromium_apk.flags:
  Ignoring option: -optimizationpasses
In ../../base/android/proguard/chromium_apk.flags:
  Ignoring option: -optimizations
Item java.lang.String org.chromium.chrome.browser.gcore.ConnectedTask.getName() was not discarded.
java.lang.String org.chromium.chrome.browser.gcore.ConnectedTask.getName()
|- is invoked from:
|  void org.chromium.chrome.browser.gcore.ConnectedTask.debugLog(java.lang.String)
|- is invoked from:
|  void org.chromium.chrome.browser.gcore.ConnectedTask.run()
|- is defined in library method overridden by:
|  org.chromium.chrome.browser.gcore.ConnectedTask
|- is reachable from:
|  com.google.android.apps.chrome.icing.IcingController$IcingLightweightTask
|- is reachable from:
|  com.google.android.apps.chrome.icing.IcingController$6
|- is instantiated in:
|  void org.chromium.chrome.browser.gsa.ContextReporter.reportUsageOfCurrentContextIfPossible(org.chromium.chrome.browser.tab.Tab,boolean,org.chromium.chrome.browser.gsa.GSAContextDisplaySelection)
|- is invoked from:
|  void org.chromium.chrome.browser.ChromeActivity.createContextReporterIfNeeded()
|- is reachable from:
|  org.chromium.chrome.browser.ChromeActivity
|- is referenced in keep rule:
|  ../../base/android/proguard/chromium_code.flags:35:1



Original change's description:
> Use assumevalues instead of assumenosideffects for proguard.
> 
> This seems to have the same meaning, however use of "return" in assumenosideffects is not working for some versions of proguard.
> 
> Change-Id: Ie6dde7612d25c7ee5fd2d2fd42dfe74444188c41
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1804064
> Reviewed-by: Sam Maier <smaier@chromium.org>
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Commit-Queue: Eric Roman <eroman@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#696911}

TBR=eroman@chromium.org,agrieve@chromium.org,smaier@chromium.org

Change-Id: Ia68d499e59e0b9e1dcda34bfa9389fa1977079b5
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1808018
Reviewed-by: Avi Drissman <avi@chromium.org>
Commit-Queue: Avi Drissman <avi@chromium.org>
Cr-Commit-Position: refs/heads/master@{#696958}