Revert of base: Remove using:: declaration from version.h header. (patchset #24 id:450001 of https://codereview.chromium.org/1281313003/ )
Reason for revert:
Broke all official bots, e.g. http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Win/builds/1926/steps/compile/logs/stdio

c:\b\build\slave\google-chrome-rel-win\build\src\chrome\browser\component_updater\pepper_flash_component_installer.cc(326) :error C3861: 'Version': identifier not found

Original issue's description:
> base: Remove using:: declaration from version.h header.
>
> BUG=None
> R=brettw@chromium.org
>
> Committed: https://crrev.com/4fed970afd06334ea392e8116513e8c98b83068e
> Cr-Commit-Position: refs/heads/master@{#344088}

TBR=brettw@chromium.org,tfarina@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=None

Review URL: https://codereview.chromium.org/1301883002

Cr-Commit-Position: refs/heads/master@{#344138}