IWYU: missing include for usage of memset in SimplePartitionStatsDumper
Fix build error with libstdc++:
    ../../base/allocator/partition_allocator/partition_stats.cc: In constructor ‘partition_alloc::SimplePartitionStatsDumper::SimplePartitionStatsDumper()’:
    ../../base/allocator/partition_allocator/partition_stats.cc:10:3: error: ‘memset’ was not declared in this scope
       10 |   memset(&stats_, 0, sizeof(stats_));
          |   ^~~~~~

Bug: 957519
Change-Id: I7f8297859f663c4ba58bae0429f33da9071bb0d7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3453062
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Reviewed-by: Benoit Lize <lizeb@chromium.org>
Cr-Commit-Position: refs/heads/main@{#970594}