Improve temp dir handling for child procs on Windows and macOS.
Tests may leak files/directories in temp due to ScopedTempDir lifetime
issues (see linked bug) or as a result of crashes. This CL augments the
TestLauncher to handle such leaks a bit better. When launching a child
proc on Windows and macOS, the TestLauncher now directs that child to
its own dedicated temporary directory. Upon child exit, the launcher
checks for leaked files/directories in that dir and deletes the dir. On
test iteration completion, the launcher will emit a list of the tests
that produced leaks when run with --test-launcher-print-temp-leaks that
looks a lot like this:

ERROR: 2 files and/or directories were left behind in the temporary directory by one or more of these tests: PaymentManagerTest.ClearPaymentInstruments:PermissionControllerImplTest.ResettingOverridesForwardsReset:PermissionControllerImplTest.SettingOverridesForwardsUpdates:PermissionControllerImplTest.RequestPermissionsDelegatesIffMissingOverrides:PermissionControllerImplTest.GetPermissionStatusDelegatesIffNoOverrides:PermissionControllerImplTest.GetPermissionStatusForFrameDelegatesIffNoOverrides:PermissionControllerImplTest.NotifyChangedSubscriptionsCallsOnChangeOnly:PermissionControllerImplTest.PermissionsCannotBeOverriddenIfNotOverridable:PermissionControllerImplTest.GrantPermissionsReturnsStatusesBeingSetIfOverridable:PictureInPictureServiceImplTest.EnterPictureInPicture

Curious developers can binary search in that short list of tests to find
the one(s) that are leaking and clean them up.

BUG=546640
TBR=sky@chromium.org

Change-Id: If3be7034094827979c225d2eb2beba2d92e6e7ce
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1978679
Commit-Queue: Greg Thompson <grt@chromium.org>
Auto-Submit: Greg Thompson <grt@chromium.org>
Reviewed-by: Erik Chen <erikchen@chromium.org>
Cr-Commit-Position: refs/heads/master@{#728475}